name: dansdata-backend

services:
  dance-api:
    build:
      context: ../
      dockerfile: src/app/Dockerfile
      additional_contexts:
        docker-helpers: ./docker-helpers/
    restart: unless-stopped
    networks:
      private:
    environment:
      DOCKER_DANCE_API_HOST_FILE: /run/secrets/docker-dance-api-host
    secrets:
      - docker-dance-api-host

  keycloak:
    build:
      context: ./auth/
      dockerfile: Dockerfile
      additional_contexts:
        docker-helpers: ./docker-helpers/
    command:
      - /opt/keycloak/bin/kc.sh
      - start
      - --optimized
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    networks:
      private:
    environment:
      DOCKER_DATABASE_HOST_FILE: /run/secrets/docker-database-host
      DB_NAME_FILE: /run/secrets/db-name
      KC_DB_USERNAME_FILE: /run/secrets/db-keycloak-user
      KC_DB_PASSWORD_FILE: /run/secrets/db-keycloak-password
      KC_HOSTNAME_FILE: /run/secrets/kc-hostname
      KC_HOSTNAME_ADMIN_FILE: /run/secrets/kc-hostname-admin
      KEYCLOAK_ADMIN_FILE: /run/secrets/keycloak-admin-user
      KEYCLOAK_ADMIN_PASSWORD_FILE: /run/secrets/keycloak-admin-password
    secrets:
      - docker-database-host
      - db-name
      - db-keycloak-user
      - db-keycloak-password
      - kc-hostname
      - kc-hostname-admin
      - keycloak-admin-user
      - keycloak-admin-password

  database:
    build:
      context: ../
      dockerfile: src/db/Dockerfile
    restart: unless-stopped
    networks:
      private:
    environment:
      ENVIRONMENT_FILE: /run/secrets/environment
      POSTGRES_USER_FILE: /run/secrets/dbms-owner-user
      POSTGRES_PASSWORD_FILE: /run/secrets/dbms-owner-password
      DB_OWNER_USER_FILE: /run/secrets/db-owner-user
      DB_OWNER_PASSWORD_FILE: /run/secrets/db-owner-password
      DB_APP_AUTH_USER_FILE: /run/secrets/db-app-auth-user
      DB_APP_AUTH_PASSWORD_FILE: /run/secrets/db-app-auth-password
      DB_KEYCLOAK_USER_FILE: /run/secrets/db-keycloak-user
      DB_KEYCLOAK_PASSWORD_FILE: /run/secrets/db-keycloak-password
      DB_NAME_FILE: /run/secrets/db-name
    secrets:
      - environment
      - dbms-owner-user
      - dbms-owner-password
      - db-owner-user
      - db-owner-password
      - db-app-auth-user
      - db-app-auth-password
      - db-keycloak-user
      - db-keycloak-password
      - db-name

  gateway:
    build:
      context: ./gateway/
      dockerfile: Dockerfile
      additional_contexts:
        docker-helpers: ./docker-helpers/
    restart: unless-stopped
    networks:
      private:
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /data/caddy:/data
      - caddy-config:/config
    environment:
      DOMAIN_API_DANSDATA_FILE: /run/secrets/domain-api-dansdata
      DOMAIN_ADMIN_DANSDATA_FILE: /run/secrets/domain-admin-dansdata
      DOCKER_DANCE_API_HOST_FILE: /run/secrets/docker-dance-api-host
      DOCKER_KEYCLOAK_HOST_FILE: /run/secrets/docker-keycloak-host
      NET_PRIVATE_SUBNET: ${NET_PRIVATE_SUBNET}
    secrets:
      - domain-api-dansdata
      - domain-admin-dansdata
      - docker-dance-api-host
      - docker-keycloak-host

  # Provides access to internal services
  # from external source.
  # Note: unusable from docker host!
  # Docker host can access services via their IP.
  vpn:
    image: linuxserver/wireguard:latest
    restart: unless-stopped
    networks:
      private:
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - vpn-config:/config
    ports:
      - 51820:51820/udp
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      SERVERURL: auto
      SERVERPORT: 51820
      PEERS: 1
      INTERNAL_SUBNET: ${VPN_SUBNET}
      ALLOWEDIPS: ${NET_PRIVATE_SUBNET}
      LOG_CONFS: false

networks:
  private:
    ipam:
      config:
        - subnet: ${NET_PRIVATE_SUBNET}
          ip_range: ${NET_PRIVATE_IP_RANGE}
          gateway: ${NET_PRIVATE_GATEWAY}

volumes:
  caddy-config:
  vpn-config:

secrets:
  environment:
    environment: ENVIRONMENT

  docker-dance-api-host:
    environment: DOCKER_DANCE_API_HOST
  docker-database-host:
    environment: DOCKER_DATABASE_HOST
  docker-keycloak-host:
    environment: DOCKER_KEYCLOAK_HOST

  domain-api-dansdata:
    environment: DOMAIN_API_DANSDATA
  domain-admin-dansdata:
    environment: DOMAIN_ADMIN_DANSDATA

  dbms-owner-user:
    environment: DBMS_OWNER_USER
  dbms-owner-password:
    environment: DBMS_OWNER_PASSWORD
  db-owner-user:
    environment: DB_OWNER_USER
  db-owner-password:
    environment: DB_OWNER_PASSWORD
  db-app-auth-user:
    environment: DB_APP_AUTH_USER
  db-app-auth-password:
    environment: DB_APP_AUTH_PASSWORD
  db-keycloak-user:
    environment: DB_KEYCLOAK_USER
  db-keycloak-password:
    environment: DB_KEYCLOAK_PASSWORD
  db-name:
    environment: DB_NAME

  kc-hostname:
    environment: KC_HOSTNAME
  kc-hostname-admin:
    environment: KC_HOSTNAME_ADMIN
  keycloak-admin-user:
    environment: KEYCLOAK_ADMIN_USER
  keycloak-admin-password:
    environment: KEYCLOAK_ADMIN_PASSWORD
